-- Migracao versionada: o Flyway aplica em ordem (V1, V2...) e registra cada
-- uma na tabela flyway_schema_history. Em producao, o schema evolui por
-- migracoes — nunca por ddl-auto.
create table employees (
    id        bigint generated by default as identity primary key,
    name      varchar(255) not null,
    email     varchar(255) unique,
    department varchar(255),
    salary    numeric(12, 2),
    hire_date date,
    active    boolean not null
);
